[build]
  publish = "_site"              # Eleventy's output directory
  command = "npm run build"      # Your build command

[build.environment]
  NODE_VERSION = "18"            # Ensure compatible Node version

# Redirect for Netlify CMS
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

# Redirect all other routes to Eleventy's index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
