<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Content Manager</title>

  <script src="https://unpkg.com/netlify-cms@^2.10.193/dist/netlify-cms.js"></script>

  <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>

  </head>
<body>
  <div id="nc-root"></div>

  <script>
    // Initialize Netlify CMS
    CMS.init({
      config: {
        backend: {
          name: 'git-gateway',
          branch: 'main'
        },
        publish_mode: 'editorial_workflow',
        media_folder: 'src/assets/images/uploads',
        public_folder: '/assets/images/uploads',
        collections: [
          {
            name: "posts",
            label: "Posts",
            folder: "src/posts",
            create: true,
            slug: "{{year}}-{{month}}-{{day}}-{{slug}}",
            fields: [
              {label: "Title", name: "title", widget: "string", required: true},
              {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", timeFormat: false, required: true},
              {label: "Category", name: "category", widget: "select", options: ["politics", "entertainment", "sports", "latest"], default: "latest", required: true},
              {label: "Featured Image", name: "image", widget: "image", required: false},
              {label: "Image Alt Text", name: "image_alt", widget: "string", required: false, hint: "Important for accessibility and SEO."},
              {label: "Excerpt", name: "excerpt", widget: "text", required: true, hint: "A short summary for news cards."},
              {label: "Body", name: "body", widget: "markdown", required: true}
            ]
          },
          {
            name: "pages",
            label: "Pages",
            folder: "src/pages",
            create: false,
            editor: {
              preview: false
            },
            files: [
              {
                file: "src/pages/about.md",
                label: "About Us",
                name: "about",
                fields: [
                  {label: "Title", name: "title", widget: "string", required: true},
                  {label: "Body", name: "body", widget: "markdown", required: true}
                ]
              },
              {
                file: "src/pages/contact.md",
                label: "Contact Us",
                name: "contact",
                fields: [
                  {label: "Title", name: "title", widget: "string", required: true},
                  {label: "Body", name: "body", widget: "markdown", required: true}
                ]
              }
            ]
          }
        ]
      }
    });

    // Optional: Netlify Identity event listener for redirecting after login
    if (window.netlifyIdentity) {
      window.netlifyIdentity.on("init", user => {
        if (!user) {
          window.netlifyIdentity.on("login", () => {
            document.location.href = "/admin/";
          });
        }
      });
    }
  </script>
</body>
</html>
