backend:
  name: git-gateway
  branch: main # Branch to update (your default branch, e.g., main)

publish_mode: editorial_workflow # Optional: Enables draft/review workflow

# Media folder should be relative to the root of your SSG's source directory
media_folder: "src/assets/images/uploads" # Where uploaded images will be stored
public_folder: "/assets/images/uploads"   # The public path to the media folder (relative to deployed site)

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts" # Eleventy will read from here
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template for new posts
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", timeFormat: false, required: true}
      - {label: "Category", name: "category", widget: "select", options: ["politics", "entertainment", "sports", "latest"], default: "latest", required: true}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Image Alt Text", name: "image_alt", widget: "string", required: false, hint: "Important for accessibility and SEO."}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: true, hint: "A short summary for news cards."}
      - {label: "Body", name: "body", widget: "markdown", required: true}
  - name: "pages"
    label: "Pages"
    folder: "src/pages" # Eleventy will read from here
    create: false # Set to false if you want to manage these pages directly in git, not via CMS UI
    editor:
      preview: false # Disable preview for simple pages if content is markdown
    files:
      - file: "src/pages/about.md"
        label: "About Us"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string", required: true}
          - {label: "Body", name: "body", widget: "markdown", required: true}
      - file: "src/pages/contact.md"
        label: "Contact Us"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string", required: true}
          - {label: "Body", name: "body", widget: "markdown", required: true}